### ISSUE TITLE
"Save As" Button Grayed Out

### ISSUE THREAD

**Issue by kadattack** [eishiya/tiled-expand-autotile#1]
I think on Linux there is an issue with code line
https://github.com/eishiya/tiled-expand-autotile/blob/d467a7565f17c05f3d408714b0545c3cf52a9108/ExpandRPGMTileset.js#L113
I get an error

> Non-existent file chosen: media/Foo/Bar/Downloads/RPGMakerResources/TileD/Project/Tile_Converter/Input/tw32th32A1Dirt.png. Tileset will not be created.

Looks like it's missing `/` at the start.
If i change the line of code to `source = url.toString().replace(/^file:\/+/, '/');` it works and it now finds the file.

**Comment by eishiya** [comment]
This should be fixed by https://github.com/eishiya/tiled-expand-autotile/commit/425206984f097d48dadf132a8330db16bac3beb4, please redownload the script. As I am not on Linux, I can't test it, but based on your report and another one recently, I think this should work now at least on Linux, but hopefully also on MacOS. The QUrl -> path conversion now checks the current OS.

The cause was that the QUrls include an extra `/` on Windows that is not normally part of the path, so since I tested on that OS, I was stripping too many slashes. This problem likely affects many other Tiled scripts that do this conversion, and certainly several of mine. An ideal fix would be for Tiled to consistently use either QUrls or file path strings, and this has been discussed, but for now, this OS-aware conversion should work. Thanks for getting me off my butt to fix this! I should go add this change to my other scripts...

Edit: Apparently the situation is even simpler: The extra `/` on Windows is simply not a problem and can be left in, so no OS-specific code is necessary :D `source = url.toString().replace(/^file:\/{2}/, '');` works perfectly fine, as far as I can tell.

Edit 2: Looks like Tiled 1.10.3 will provide a way to get a file path directly from the FilePicker, so no conversion will be necessary :D https://github.com/mapeditor/tiled/pull/3893 I will make the relevant change once 1.10.3 is released.

**Comment by GeorgesGraire** [comment]
It still doesn't seems to work with the latest version of the script...
![image](https://github.com/eishiya/tiled-expand-autotile/assets/82153698/17b680a4-4106-46d7-8307-01fccec7e92b)

**Comment by eishiya** [comment]
Since I can't reproduce this issue, could you please provide more information?

~~1. Does your version of the script have `source = url.toString().replace(/^file:\/{2}/, '');` as line 113? (i.e. the actual latest version of the script).
2. Can you please add `tiled.log(url); tiled.log(source);` after that line and show me the output? The output will show up in the Tiled console, which you can view by clicking the dark button in the bottom left of the Tiled window. You can edit out any sensitive info from the output.
3. What OS and Tiled version are you using?~~

Edit: Looks like I can reproduce this after all. Investigating. Looks like the previous version of the script, with Windows-specific code, did work, but the "universal" one doesn't. I thought I tested this. Please use the version of the script linked in the previous comment, it should work. I will update the newest one as well.

**Comment by eishiya** [comment]
I've brought back the Windows-specific URL handling, the newest version should work for you. Thanks, @GeorgesGraire!
